### ISSUE TITLE
css in not formatted correctly

### ISSUE THREAD

**Issue by fusco** [laurent-galan/exercice-fallout#1]
```css
body{radial-gradient:;}
h1{font-size: 4em;
	font-weight: 900;
	margin-top: 15%;}

ul{margin-left: -2%;
	font-size: 1.2em;
	line-height: 30px;}
```

```css
body { 
   radial-gradient: IL manque un truc là 
}

h1 {
    font-size: 4em;
    font-weight: 900;
    margin-top: 15%;
}

ul {
   margin-left: -2%;
   font-size: 1.2em;
   line-height: 30px;
}
```
